server:
  port: 8080

spring:
  application:
    name: gym-core

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,mappings
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      gym-security:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true
      workload-service:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: true

feign:
  circuitbreaker:
    enabled: true