version: '3.8'

services:
  postgres:
    container_name: gym-core-postgres
    image: postgres:latest
    shm_size: 128mb
    ports:
      - "5430:5432"
    environment:
      POSTGRES_DB: gym_crm
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    restart: always